name = "BellmanPDEs"
uuid = "f5c2d71c-83f8-4255-b29d-cee59dfde9e8"
authors = ["William Pope"]
version = "0.1.0"

[deps]
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
